name: PersonalChest
version: 1.2.0
main: nl.rodey.personalchest.pchestMain
commands:
   pchest:
      description: Register or unregister the Chest with these commands or check if registered.
      usage: /pchest [CREATE|REMOVE|INFO]
permissions:
   pchest.edit:
      description: Create or Remove PersonalChests
      default: op
   pchest.open:
      description: Open and use PersonalChests
      default: true
